global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.EntityFrameworkCore;
global using Fitmaniac.Application.Common;
global using Fitmaniac.Domain.Entities;
global using Fitmaniac.Domain.Enums;
